from dotenv import dotenv_values
from pathlib import Path


BASE_PATH = Path(__file__).parent.parent
ENV = dotenv_values(BASE_PATH / '.env')
DB_STAGING_HOST = ENV['DB_STAGING_HOST']
DB_STAGING_PORT = ENV['DB_STAGING_PORT']
DB_STAGING_NAME = ENV['DB_STAGING_NAME']
DB_STAGING_USER = ENV['DB_STAGING_USER']
DB_STAGING_PASSWORD = ENV['DB_STAGING_PASSWORD']
LOG_FILE_PATH = BASE_PATH / ENV['LOG_FILE_PATH']
LIMIT_LOG_WRITES_PER_HOUR = int(ENV['LIMIT_LOG_WRITES_PER_HOUR'])
